name: Maven build

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  mvn:
    uses: netcracker/qubership-core-infra/.github/workflows/run-maven-with-sonar.yaml@v1.0.2
    with:
      event-name: ${{ github.event_name }}
      actor: ${{ github.actor }}
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}
